# Generated by Django 3.2.4 on 2021-10-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZyjWechatManufactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='生产商名称')),
                ('manufactor_introduction', models.CharField(max_length=256, verbose_name='生产商简介')),
                ('manufactor_logo', models.CharField(max_length=512, verbose_name='商标')),
                ('manufactor_sample', models.CharField(max_length=512, verbose_name='宣传图')),
            ],
        ),
        migrations.CreateModel(
            name='ZyjWechatRetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128, unique=True, verbose_name='店铺名称')),
                ('master_name', models.CharField(max_length=128, verbose_name='负责人名称')),
                ('phone', models.CharField(max_length=32, verbose_name='客服手机号码')),
                ('qq_number', models.CharField(max_length=32, verbose_name='客服qq号码')),
                ('wechat_number', models.CharField(max_length=64, verbose_name='客服微信号码')),
                ('address', models.CharField(max_length=128, verbose_name='店铺地址')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
                ('shop_introduction', models.CharField(max_length=256, verbose_name='店铺简介')),
                ('Product', models.ManyToManyField(to='wechat.ZyjWechatManufactor')),
            ],
            options={
                'verbose_name': '零售商',
                'verbose_name_plural': '零售商集合',
            },
        ),
        migrations.CreateModel(
            name='ZyjWechatInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.IntegerField(choices=[(1, '一级邀请码'), (2, '二级邀请码'), (3, '三级邀请码')])),
                ('invitation_code', models.CharField(max_length=64, unique=True, verbose_name='邀请码')),
                ('effective_time', models.IntegerField(default=3, verbose_name='有效时间')),
                ('Retail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.zyjwechatretail')),
            ],
        ),
        migrations.CreateModel(
            name='CodeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('first_loading', models.DateTimeField(auto_now_add=True, verbose_name='首次登陆时间')),
                ('token_effective_time', models.IntegerField(default=3, verbose_name='有效时间')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.zyjwechatinvitationcode')),
            ],
        ),
    ]
