# Generated by Django 3.2.4 on 2021-10-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetoken',
            options={'verbose_name': 'token', 'verbose_name_plural': 'token'},
        ),
        migrations.AlterModelOptions(
            name='zyjwechatinvitationcode',
            options={'verbose_name': '邀请码', 'verbose_name_plural': '邀请码集合'},
        ),
        migrations.AlterModelOptions(
            name='zyjwechatmanufactor',
            options={'verbose_name': '生产商', 'verbose_name_plural': '生产商集合'},
        ),
        migrations.AlterField(
            model_name='zyjwechatmanufactor',
            name='manufactor_sample',
            field=models.CharField(max_length=1024, verbose_name='宣传图'),
        ),
        migrations.CreateModel(
            name='ZyjWechatEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='版本名称')),
                ('style', models.CharField(max_length=128, verbose_name='版本风格')),
                ('date', models.CharField(max_length=128, verbose_name='版本上线日期')),
                ('manufactor_sample', models.CharField(max_length=1024, verbose_name='宣传图')),
                ('Manufactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.zyjwechatmanufactor')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本集合',
            },
        ),
    ]
