# Generated by Django 3.0.8 on 2021-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20211101_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zyjwechatmodel',
            options={'verbose_name': '型号', 'verbose_name_plural': '型号集合'},
        ),
        migrations.AddField(
            model_name='zyjwechatmodel',
            name='VR_QR',
            field=models.CharField(max_length=1024, null=True, verbose_name='实景图二维码'),
        ),
    ]
