# Generated by Django 3.0.8 on 2021-11-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_zyjwechatartificial_zyjwechatingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='名称')),
                ('phone', models.CharField(max_length=32, verbose_name='客服手机号码')),
                ('address', models.CharField(max_length=128, verbose_name='店铺地址')),
                ('reduction', models.CharField(max_length=128, null=True, verbose_name='满减')),
                ('images_small', models.CharField(max_length=1024, null=True, verbose_name='图片')),
                ('remaining', models.FloatField(max_length=64, null=True, verbose_name='剩余个数')),
                ('state', models.FloatField(max_length=64, null=True, verbose_name='状态')),
                ('verification', models.FloatField(max_length=64, null=True, verbose_name='验证码')),
                ('Retail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.ZyjWechatRetail')),
            ],
            options={
                'verbose_name': '满减券',
                'verbose_name_plural': '满减券',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, unique=True, verbose_name='名称')),
                ('product_name', models.CharField(max_length=128, null=True, verbose_name='品牌名称')),
                ('images_small', models.CharField(max_length=1024, null=True, verbose_name='图片')),
                ('images_big', models.CharField(max_length=1024, null=True, verbose_name='图片')),
                ('reference_price', models.FloatField(max_length=64, null=True, verbose_name='参考价格')),
                ('characteristic', models.FloatField(max_length=64, null=True, verbose_name='图案类型')),
                ('discount', models.BooleanField(null=True, verbose_name='折扣商品')),
                ('Retail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.ZyjWechatRetail')),
            ],
            options={
                'verbose_name': '种类',
                'verbose_name_plural': '种类集合',
            },
        ),
    ]
