# Generated by Django 3.0.8 on 2021-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20211123_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, null=True, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='设备名称')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='类型')),
                ('state', models.CharField(max_length=32, null=True, verbose_name='状态')),
                ('time', models.CharField(max_length=32, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '甲醛检测',
                'verbose_name_plural': '甲醛检测',
            },
        ),
    ]
