# Generated by Django 3.0.8 on 2021-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0013_methanal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methanal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='methanal',
            name='password',
        ),
        migrations.RemoveField(
            model_name='methanal',
            name='state',
        ),
        migrations.RemoveField(
            model_name='methanal',
            name='type',
        ),
        migrations.AddField(
            model_name='methanal',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='methanal',
            name='invitation_code',
            field=models.CharField(max_length=128, null=True, verbose_name='邀请码'),
        ),
        migrations.AddField(
            model_name='methanal',
            name='methanal_value',
            field=models.CharField(max_length=1024, null=True, verbose_name='甲醛含量'),
        ),
        migrations.AlterField(
            model_name='methanal',
            name='number',
            field=models.CharField(max_length=128, null=True, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='methanal',
            name='time',
            field=models.CharField(max_length=32, null=True, verbose_name='时间'),
        ),
    ]
