# Generated by Django 3.0.8 on 2021-12-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0014_auto_20211202_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methanal',
            name='address',
        ),
        migrations.AddField(
            model_name='methanal',
            name='ip',
            field=models.CharField(max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='methanal',
            name='port',
            field=models.CharField(max_length=32, null=True, verbose_name='端口'),
        ),
    ]
