# Generated by Django 3.0.8 on 2021-12-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0015_auto_20211203_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, null=True, verbose_name='设备编号')),
                ('invitation_code', models.CharField(max_length=128, null=True, verbose_name='邀请码')),
            ],
        ),
    ]
