# Generated by Django 3.0.8 on 2021-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0016_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip',
            field=models.CharField(max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='port',
            field=models.CharField(max_length=32, null=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='number',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='设备编号'),
        ),
    ]
