# Generated by Django 3.0.8 on 2021-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0017_auto_20211204_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='methanal',
            name='status',
            field=models.CharField(max_length=32, null=True, verbose_name='状态'),
        ),
    ]
