# Generated by Django 3.0.8 on 2021-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0018_methanal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methanal',
            name='status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(max_length=32, null=True, verbose_name='状态'),
        ),
    ]
