# Generated by Django 3.2.9 on 2022-02-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0024_remove_zyjwechatinvitationcode_liveroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveroom',
            options={'verbose_name': '直播间', 'verbose_name_plural': '直播间集合'},
        ),
    ]
