# Generated by Django 3.2.9 on 2022-02-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0025_alter_liveroom_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveRoom',
        ),
    ]
