# Generated by Django 3.2.9 on 2022-02-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0027_liveroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveRoom',
            new_name='LivingRoom',
        ),
    ]
