# Generated by Django 3.2.9 on 2022-02-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0028_rename_liveroom_livingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyjwechatinvitationcode',
            name='LiveRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.livingroom'),
        ),
    ]
