# Generated by Django 3.2.9 on 2022-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0029_zyjwechatinvitationcode_liveroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyjwechatretail',
            name='advertiser',
            field=models.CharField(max_length=128, null=True, verbose_name='下游广告商'),
        ),
    ]
