# Generated by Django 3.2.9 on 2022-02-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0030_zyjwechatretail_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=32, null=True, verbose_name='券名')),
                ('ticket_image', models.CharField(max_length=128, null=True, verbose_name='券缩略图')),
                ('ticket_image_detail', models.CharField(max_length=128, null=True, verbose_name='券详情图')),
                ('ticket_active', models.BooleanField(max_length=128, null=True, verbose_name='是否有效')),
                ('ticket_type', models.CharField(max_length=32, null=True, verbose_name='券类型')),
                ('ticket_information', models.CharField(max_length=1024, null=True, verbose_name='券说明')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
                ('Retail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.zyjwechatretail')),
            ],
        ),
    ]
