# Generated by Django 3.2.9 on 2022-02-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0031_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZyjWechatBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128, null=True, verbose_name='客户名称')),
                ('cost_name', models.CharField(max_length=128, null=True, verbose_name='费用名称')),
                ('unit_price', models.CharField(max_length=128, null=True, verbose_name='单价')),
                ('quantity', models.CharField(max_length=128, null=True, verbose_name='数量')),
                ('trading_time', models.CharField(max_length=128, null=True, verbose_name='交易时间')),
                ('InvitationCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.zyjwechatinvitationcode')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单集合',
            },
        ),
    ]
