# Generated by Django 3.2.9 on 2022-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0033_zyjwechatbill_chart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyjwechatbill',
            name='remark',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
    ]
