# Generated by Django 3.2.9 on 2022-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0035_zyjwechatbill_retail'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyjwechatinvitationcode',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='名字'),
        ),
    ]
