# Generated by Django 3.2.9 on 2022-04-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0037_auto_20220304_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('order_local', models.CharField(max_length=64, null=True, verbose_name='预约地点')),
                ('order_owner', models.CharField(max_length=32, null=True, verbose_name='客户姓名')),
                ('order_time', models.CharField(max_length=32, null=True, verbose_name='预约时间')),
                ('order_phone', models.CharField(max_length=32, null=True, verbose_name='电话')),
                ('order_code', models.CharField(max_length=32, null=True, verbose_name='邀请码')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_create_time', models.DateTimeField(auto_now_add=True, verbose_name='临时选中商品的时间')),
                ('cart_code', models.CharField(max_length=32, null=True, verbose_name='邀请码')),
                ('Classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.classification')),
            ],
            options={
                'verbose_name': '临时选中的商品',
                'verbose_name_plural': '临时选中的商品',
            },
        ),
    ]
