# Generated by Django 3.2.9 on 2022-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0038_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='characteristic',
            field=models.CharField(max_length=64, null=True, verbose_name='图案类型'),
        ),
    ]
