# Generated by Django 3.2.9 on 2023-03-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0039_alter_classification_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_type_id', models.CharField(max_length=128, null=True, verbose_name='颜色类型名称')),
                ('color_type_pic', models.CharField(max_length=128, null=True, verbose_name='单元图')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '颜色类型名称',
                'verbose_name_plural': '颜色类型名称集合',
            },
        ),
        migrations.CreateModel(
            name='ColorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=32, null=True, verbose_name='色号编码')),
                ('color_name', models.CharField(max_length=128, null=True, verbose_name='色号名称')),
                ('color_type', models.CharField(max_length=32, null=True, verbose_name='色号类型')),
                ('color_unit_pic', models.CharField(max_length=128, null=True, verbose_name='单元图')),
                ('color_pic_1', models.CharField(max_length=128, null=True, verbose_name='效果图1')),
                ('color_pic_2', models.CharField(max_length=128, null=True, verbose_name='效果图1')),
                ('color_pic_3', models.CharField(max_length=128, null=True, verbose_name='效果图1')),
                ('color_pic_4', models.CharField(max_length=128, null=True, verbose_name='效果图1')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
                ('Retail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat.colortype')),
            ],
        ),
    ]
