# Generated by Django 3.2.9 on 2023-03-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0040_colortype_colorunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=128, null=True, verbose_name='颜色简码')),
                ('color_rgb', models.CharField(max_length=128, null=True, verbose_name='颜色RGB')),
                ('hubuse_name', models.CharField(max_length=128, null=True, verbose_name='互补色简码')),
                ('hubuse_rgb', models.CharField(max_length=128, null=True, verbose_name='互补色RGB')),
                ('leibise_name', models.CharField(max_length=128, null=True, verbose_name='类比色简码')),
                ('leibise_rgb', models.CharField(max_length=128, null=True, verbose_name='类比色RGB')),
                ('jianbianse_name', models.CharField(max_length=128, null=True, verbose_name='类比色简码')),
                ('jianbianse_rgb', models.CharField(max_length=128, null=True, verbose_name='类比色RGB')),
                ('color_type', models.CharField(max_length=128, null=True, verbose_name='颜色类别')),
                ('color_system', models.CharField(max_length=128, null=True, verbose_name='颜色色系')),
                ('remark', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '全色卡名称',
                'verbose_name_plural': '全色卡名称集合',
            },
        ),
    ]
